version: "3.7"
services:
  postgres_dsmovie:
    container_name: dsmovie
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"